---
title: "Explorando padrões de letras de músicas por meio de análise de cluster e otimização bayesiana"
date: "Última atualização em `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: simplex
    css: src/style.css
    toc: true
    toc_float:
      smooth_scroll: false
editor_options: 
  chunk_output_type: inline
---

```{r echo=F, include=F}
source("src/utils.R")
```

## Web scraping

```{r}
genres <- c("bossa-nova", "funk-carioca", "gospel", "mpb", "pagode", "sertanejo")

all_artists_link <- future_map(genres, ~get_artist_link(.,15)) %>%
  unlist()
```

```{r}
tic()
all_artists <- future_map_dfr(all_artists_link, ~scrap_artist(.)) %>%
  filter(!is.na(Alink))
toc()
# com 5 gêneros demorou 5min

tic()
all_songs <- future_map_dfr(all_artists_link, ~scrap_lyrics_link(.,5)) %>%
  filter(!is.na(Slink))
toc()
# com 5 gêneros demorou 2min

tic()
all_songs$Slyrics <- future_map_chr(all_songs$Slink, ~scrap_lyric(.)[1], .progress = TRUE)
toc()
# com 5 gêneros demorou 30m

tic()
data_songs <- all_songs %>%
  select(Slink, Slyrics) %>%
  rename(link = Slink, lyrics = Slyrics) %>%
  unique()
toc()
# com 5 gêneros demorou 1s

tic()
data_songs$Slyrics <- data_songs$lyrics %>%
  str_replace_all("\\. \\. ", ". ")
toc()

tic()
data_songs <- data_songs %>%
  mutate(
    language = detect_language(lyrics),
    lyrics = gsub("\\d+", "", lyrics) %>% tolower() %>% gsub("[[:punct:]]", "", .)
  ) %>%
  filter(language == "pt") %>%
  select(-language)
toc()
# com 5 gêneros demorou 7s
```

```{r}
# write.csv(all_artists, "src/all_artists.csv")
# write.csv(all_songs, "src/all_songs.csv")
# write.csv(data_songs, "src/data_songs.csv")
```

```{r}

```

## Gabarito

```{r}
data <- read.csv("src/data_gabarito.csv")

gabarito <- data[1,] %>%
  t() %>%
  as.data.frame() %>%
  rename(sentimentos = 1) %>%
  mutate(
    anger = ifelse(grepl("Raiva", sentimentos), 1, 0),
    anticipation = ifelse(grepl("Antecipação", sentimentos), 1, 0),
    disgust = ifelse(grepl("Desgosto", sentimentos), 1, 0),
    fear = ifelse(grepl("Medo", sentimentos), 1, 0),
    joy = ifelse(grepl("Alegria", sentimentos), 1, 0),
    sadness = ifelse(grepl("Tristeza", sentimentos), 1, 0),
    surprise = ifelse(grepl("Surpresa", sentimentos), 1, 0),
    trust = ifelse(grepl("Confiança", sentimentos), 1, 0),
    negative = ifelse(grepl("Negativo", sentimentos), 1, 0),
    positive = ifelse(grepl("Positivo", sentimentos), 1, 0),
  ) %>%
  select(-sentimentos)

row.names(gabarito) <- NULL

data_gabarito <- cbind(data_songs[1:100,], gabarito)
```


## Pacote syuzhet

```{r}
tic()
syuzhet <- future_map_dfr(data_songs$lyrics, ~syuzhet_classification(., 0.05))
data_syuzhet <- cbind(data_songs, syuzhet)
toc()
```

```{r}
data_syuzhet
```

### Matriz de confusão

```{r}
data_gabarito_factor <- lapply(data_gabarito[1:100, 4:13], factor)
data_syuzhet_factor <- lapply(data_syuzhet[1:100, 4:13], factor)

confusionMatrix(unlist(data_syuzhet_factor), unlist(data_gabarito_factor))
```


## Chat GPT

```{r}
data <- read.csv("src/data_gpt.csv")

gpt <- data[1,] %>%
  t() %>%
  as.data.frame() %>%
  rename(sentimentos = 1) %>%
  mutate(
    anger = ifelse(grepl("Raiva", sentimentos), 1, 0),
    anticipation = ifelse(grepl("Antecipação", sentimentos), 1, 0),
    disgust = ifelse(grepl("Desgosto", sentimentos), 1, 0),
    fear = ifelse(grepl("Medo", sentimentos), 1, 0),
    joy = ifelse(grepl("Alegria", sentimentos), 1, 0),
    sadness = ifelse(grepl("Tristeza", sentimentos), 1, 0),
    surprise = ifelse(grepl("Surpresa", sentimentos), 1, 0),
    trust = ifelse(grepl("Confiança", sentimentos), 1, 0),
    negative = ifelse(grepl("Negativo", sentimentos), 1, 0),
    positive = ifelse(grepl("Positivo", sentimentos), 1, 0),
  ) %>%
  select(-sentimentos)

row.names(gpt) <- NULL

data_gpt <- cbind(data_songs[1:44,], gpt[1:44,])
```

### Matriz de confusão

```{r}
data_gabarito_factor <- lapply(data_gabarito[1:44, 4:13], factor)
data_gpt_factor <- lapply(data_gpt[1:44, 4:13], factor)

confusionMatrix(unlist(data_gpt_factor), unlist(data_gabarito_factor))
```

## Maritaka


## Gemini


## Modelo
```{r}
# Criar um iterador sobre os documentos
it <- itoken(
  data_songs$lyrics,
  preprocessor = tolower,
  tokenizer = word_tokenizer,
  progressbar = FALSE)

# Criar vocabulário
vocab <- create_vocabulary(it)
vectorizer <- vocab_vectorizer(vocab)

# Criar Document-Term Matrix (DTM)
dtm <- create_dtm(it, vectorizer)

# Criar e ajustar o modelo TF-IDF
tfidf_model <- TfIdf$new()
dtm_tfidf <- fit_transform(dtm, tfidf_model)
```

```{r}
# Preparar uma lista para armazenar os modelos
models <- list()

# Preparar uma matriz de features (X)
# A matriz deve ser criada a partir dos vetores TF-IDF gerados anteriormente.
# Por simplicidade, estou usando 'dtm_tfidf' como um nome de placeholder aqui.
dtm_tfidf_subset <- dtm_tfidf[1:nrow(data_gabarito), ]
X <- dtm_tfidf_subset

# Iterar sobre cada emoção e criar um modelo
for(emotion in names(data_gabarito)[4:13]) {
  # A coluna atual é a variável resposta (Y)
  Y <- data_gabarito[[emotion]]
  
  # Ajustar o modelo de regressão logística
  fit <- cv.glmnet(x = X, y = Y, family = "binomial")
  
  # Armazenar o modelo
  models[[emotion]] <- fit
}

```

```{r}
# Estrutura para armazenar resultados de avaliação
evaluation_results <- data.frame(
  Emotion = character(),
  Accuracy = numeric(),
  Sensitivity = numeric(),
  Specificity = numeric(),
  stringsAsFactors = FALSE
)

# Calcular previsões e métricas para cada modelo
for(emotion in names(models)) {
  # Fazer previsões no conjunto de teste
  predictions <- predict(models[[emotion]], newx = test_matrix, s = "lambda.min", type = "class")
  
  # Obter a verdade real
  actual <- test_data[[emotion]]
  
  # Calcular métricas de avaliação
  confusion_matrix <- table(Predicted = predictions, Actual = actual)
  accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
  sensitivity <- confusion_matrix[2, 2] / sum(confusion_matrix[2, ])
  specificity <- confusion_matrix[1, 1] / sum(confusion_matrix[1, ])
  
  # Armazenar resultados
  evaluation_results <- rbind(evaluation_results, data.frame(
    Emotion = emotion,
    Accuracy = accuracy,
    Sensitivity = sensitivity,
    Specificity = specificity
  ))
}

```


